env:  
    browser: true  
    es2021: true  
    node: true  
extends:  
    - plugin:vue/vue3-essential  
    - eslint:recommended  
    - plugin:@typescript-eslint/recommended  
    - plugin:prettier/recommended  
overrides:  
    - files:  
        - '*.ts'  
        - '*.tsx'  
        - '*.vue'  
parser: vue-eslint-parser  
parserOptions:  
    ecmaVersion: latest  
    sourceType: module  
parser: '@typescript-eslint/parser'  
plugins:  
    - vue  
    - '@typescript-eslint'  
globals: {
    uni: true,
    wx: true
}

rules: {  
    'vue/multi-word-component-names': 'off',  
    'prettier/prettier': 2,  
    quotes: ['error', 'single'],  
    eqeqeq: 'error',  
    curly: 'error',  
    semi: 0,
    no-unused-vars: 
    - error
    - args: "none"  # 不允许未使用的参数
    - vars: "all"   # 不允许任何未使用的变量
    - caughtErrors: "all"  # 不允许未使用的异常变量  
}