env:
  browser: true
  es2021: true
  node: true

extends:
  - plugin:vue/vue3-essential
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.vue'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - vue
  - '@typescript-eslint'

globals:
  uni: true
  wx: true

rules:
  no-unused-vars:
    - 'error'
    - args: 'none'
    - vars: 'all'
    - caughtErrors: 'all'

  'vue/multi-word-component-names': 'off'
  'prettier/prettier': 'error' # 修改为 'error' 或 'warn'，根据需要配置
  quotes:
    - 'error'
    - 'single'
  eqeqeq: 'error'
  curly: 'error'
  semi: 0
